spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:men:testdb
    username: sa
    password:
    schema: classpath:datas/schema.sql
    data: classpath:datas/data.sql
    initialization-mode: embedded
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

redis:
  host: 127.0.0.1
  port: 6379
  database: 0
