spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.157.239:3306/dev?setUnicode=true&characterEncoding=utf8
    username: root
    password: hy10236
#    hsql:
#      driver-class-name: org.hsqldb.jdbc.JDBCDriver
#      jdbc-url: jdbc:hsqldb:file:testdb
#      username: sa
#      password:
#    hikari:
#      auto-commit: false
#      connection-timeout: 3000
#      validation-timeout: 3000
#      max-lifetime: 60000
#      maximum-pool-size: 20
#      minimum-idle: 1
  redis:
    host: 120.79.157.239
    port: 6379
    database: 0