spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem://localhost/testdb;shutdown=true
    username: sa
    password: d41d8cd98f00b204e9800998ecf8427e
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  redis:
    host: 120.24.218.7
    port: 6379
    database: 0
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl